### ISSUE TITLE
Error in setting object position

### ISSUE THREAD

**Issue by priyankatgit** [bartmcleod/VrmlParser#1]
Hi @bartmcleod 
So after long time I have started wroking on threejs and vrml object. I hope you have remember that I have raised an [issue at threejs repository ](https://github.com/mrdoob/three.js/issues/9514).
Let's come to the point, now I am getting error when I am trying to set object position because I want to show different component at different location on PCB. I have attached image where you can see the error.

```
var loader = new $wnd.THREE.VRMLLoader();
    loader.load( 'C_0402.wrl', function ( object ) {
        object.position.set( 8.8, 39.6, 1 );
        group.add( object );
    } );
```

![vrml_issue1](https://cloud.githubusercontent.com/assets/2055200/18982050/e86a9eee-8700-11e6-80d3-5ba0bd2d25c4.png)

**Comment by bartmcleod** [comment]
Just a very quick first thought: Currently I am not using the VRMLLoader from THREE, so I cannot be sure that it is working. I load the world like you can see in `example.html`, using the XHRLoader directly. After that, you can find your object by `var obj = scene.getObjectByName('name of object');`. After that, the call to `obj.position.set()` should work as expected.

Please make sure you git clone _this_ repository and then run `npm install` or create a new project with `npm install VrmlParser`. 

I'll be happy to look into this issue in more detph later, if the above doesn't solve it for you.

**Comment by priyankatgit** [comment]
Indeed it works. You can close the issue.
Thanks
