### ISSUE TITLE
Expected "{" or value but "[" found on believed valid VRML

### ISSUE THREAD

**Issue by Sonander** [bartmcleod/VrmlParser#12]
The attached file was written by CAD Exchanger and is believed valid.

The error looks like one we had on other files that were fixed by 'issue #5 where a coordIndex need not end with -1' but it happens on this file even with your code containing that fix. 

[350988.wrl.zip](https://github.com/bartmcleod/VrmlParser/files/3003889/350988.wrl.zip)

If you could look at this and comment it would be much appreciated.

Jeremy

**Comment by bartmcleod** [comment]
The problem was the identifier on line 4, that is a single underscore "_". The parser did not allow this, but now it does. Fixed in version 0.8.2

**Comment by Sonander** [comment]
Hi Bart,

Thank you for this amazingly quick work. We really appreciate that and can confirm its now working well for us.

Jeremy.

**Comment by bartmcleod** [comment]
Thanks for the heads up :-)
