### ISSUE TITLE
Parsing error on attached vrml file

### ISSUE THREAD

**Issue by Sonander** [bartmcleod/VrmlParser#13]
On the attached file which was generated by CAD Exchanger, I get an error in vlml.min.js, line 67 saying
undefined is not an object (evaluating 'y.r')

Please could you let me know if this is an issue with the parser or a problem with the vrml I need to take up with CAD Exchanger?

Looking forward to your reply. 

Jeremy

[12975638.wrl.zip](https://github.com/bartmcleod/VrmlParser/files/5438804/12975638.wrl.zip)

**Comment by bartmcleod** [comment]
@Sonander I suspect the DEF names starting with two underscores a not supported by the parser, but this is just from the top of my head. Will look into it later. You might want to try replacing these `__` with `aa` and see if that helps.

**Comment by Sonander** [comment]
Thank you for the suggestion. I tried a global replace of __ with aa and the parsing error is unchanged.

**Comment by bartmcleod** [comment]
Ok, so we ruled that one out. I will investigate later.

**Comment by bartmcleod** [comment]
@Sonander There is no issue with the VRML file. There is no issue with the parser. The issue is in the renderer that converts the VRML nodes to Three. Will look into that.

**Comment by bartmcleod** [comment]
@Sonander This issue is now fixed in v0.8.3 and master. 

However, when I load the file in the example page I still see a lot of other warnings (all the same on it seems), which are known, but which so far I have not been able to pinpoint [Edit: I have pinpointed it now, it is about trying to determine the bounding sphere of a single point, which is pointless, pun intended, as the bounding sphere of a single point should be the point itself and as it happens, it had no boundingSphere defined. You can solve this by removing the PointSet that represents origin (0,0,0) from your vrml file ]. I also do not see anything in the view, it is black.

The error I see repeated many times is:
```
three.js:8220 Uncaught TypeError: Cannot read property 'center' of undefined
    at Sphere.copy (three.js:8220)
    at Frustum.intersectsObject (three.js:8634)
```

This is likely not related to anything specific in your file.

Please test and confirm that the original issue is fixed by closing it.

**Comment by Sonander** [comment]
I see a similar outcome allowing for browser messaging differences. 
The parsing completes and now three.js now gets stuck in a loop endlessly cranking out the error messages below. 

It's not clear how I proceed from here, but I thank you for fixing the parser so promptly. 

[Error] TypeError: undefined is not an object (evaluating 'a.center')
	copy (three.min.js:482:163)
	(anonymous function) (three.min.js:490)
	k (three.min.js:155)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	(anonymous function) (three.min.js:190:94)
	renderChip (3D.php:79)
	dispatchEvent (three.min.js:295:131)
	(anonymous function) (TrackballControls.js:326)
	resetZoom (3D.php:511)
	(anonymous function) (3D.php:166)
	(anonymous function)
	(anonymous function) (three.min.js:650:138)
[Error] TypeError: undefined is not an object (evaluating 'a.center')
	copy (three.min.js:482:163)
	(anonymous function) (three.min.js:490)
	k (three.min.js:155)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	(anonymous function) (three.min.js:190:94)
	renderChip (3D.php:79)
	dispatchEvent (three.min.js:295:131)
	(anonymous function) (TrackballControls.js:326)
	animate (3D.php:215)
[Error] TypeError: undefined is not an object (evaluating 'a.center')
	copy (three.min.js:482:163)
	(anonymous function) (three.min.js:490)
	k (three.min.js:155)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	(anonymous function) (three.min.js:190:94)
	renderChip (3D.php:79)
	onWindowResize (3D.php:307)
[Error] TypeError: undefined is not an object (evaluating 'a.center')
	copy (three.min.js:482:163)
	(anonymous function) (three.min.js:490)
	k (three.min.js:155)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	(anonymous function) (three.min.js:190:94)
	renderChip (3D.php:79)
	dispatchEvent (three.min.js:295:131)
	(anonymous function) (TrackballControls.js:326)
	animate (3D.php:215)
[Error] TypeError: undefined is not an object (evaluating 'a.center')
	copy (three.min.js:482:163)
	(anonymous function) (three.min.js:490)
	k (three.min.js:155)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	k (three.min.js:155:367)
	(anonymous function) (three.min.js:190:94)
	renderChip (3D.php:79)
	dispatchEvent (three.min.js:295:131)
	(anonymous function) (TrackballControls.js:326)
	animate (3D.php:215)

**Comment by bartmcleod** [comment]
@Sonander To get rid of the error messages, remove the `PointSet` that represents the origin from the vrml file. A PointSet with a single point (origin) apparently has no BoundingSphere and thus that does not have a center, hence the error messages. They are caused by animate() by the way, so if you don't need that, you can turn it off.

**Comment by Sonander** [comment]
Thank you! I found if I deleted the section containing the PointSet the part loaded perfectly. 
Specifically this:

`        DEF COMPOUND011 Group {
          children [
            DEF COMPOUND011_1 Shape {
              appearance DEF __19 Appearance {
                material DEF __20 Material {
                  ambientIntensity 0.25
                  shininess 0
                }
              }
              geometry DEF __21 PointSet {
                coord Coordinate {
                  point [
                    0 0 0

                  ]
                }
              }
            }
          ]
        }`

Without which I see the attached. 

This gives me a way for checking other vrml files for the issue and possibly creating a test case for three.js
Thanks again!

Jeremy

![Screenshot 2020-10-29 at 10 50 27](https://user-images.githubusercontent.com/31996566/97558842-92b48f80-19d4-11eb-9ee3-881a3099904b.png)

**Comment by bartmcleod** [comment]
You're very welcome!
