### ISSUE TITLE
Exception thrown parsing this VRML file

### ISSUE THREAD

**Issue by Sonander** [bartmcleod/VrmlParser#14]
Odd this, for 2 years the parser has worked flawlessly, then two possible issues pop up on the same day. 

In this one an exception is caught in my code, but the only thing in the associated try is the vrml parser. 
The exception text is 
Exception with message Expected "{" or value but "[" found.

Again it's CAD Exchanger generated VRML and once again I would be grateful if you could tell me if this is an issue with the VRML or the parser.  VRML is attached. 

Thanks in advance for any guidance you can supply. 

Jeremy

[307822.wrl.zip](https://github.com/bartmcleod/VrmlParser/files/5438935/307822.wrl.zip)

**Comment by bartmcleod** [comment]
There is a syntax error in the file: `DEF -+¦+ Group`

**Comment by Sonander** [comment]
Thank you. I have reported this issue to the developers of CAD Exchanger.
