### ISSUE TITLE
Load Inline Models

### ISSUE THREAD

**Issue by mobilinkd** [bartmcleod/VrmlParser#9]
@bartmcleod This is an enhancement request.

Please support the loading of inline models referenced via URL to avoid having to merge the model files.  For electronic components which use dozens of the same part, it can increase the total size of the merged file considerably.

**Comment by bartmcleod** [comment]
@mobilinkd I have added support for Inline models in version 0.8.2. Can you check if this works for you? I have only tested with `wrl/Inline.wrl`, which loads three other models from the same directory.
